#include "kernel/include/types.h"
#include "xv6-user/user.h"
#include "xv6-user/pmu.h"

// These functions are already declared in user.h and generated by usys.pl
// So, this file (pmu.c) might not be strictly necessary if you only have these
// direct mappings. However, it's a good place for more complex user-level
// PMU utility functions if you develop them later.

// Example of a helper that could live here:
// int pmu_count_set_bits(unsigned long mask) {
//     int count = 0;
//     while (mask > 0) {
//         mask &= (mask - 1);
//         count++;
//     }
//     return count;
// }

// For now, pmu.c might be empty or contain more advanced helper functions
// if you decide the direct syscalls `pmu_setup()` and `pmu_control()` from user.h
// are sufficient.
// If we don't add any more complex wrappers, then user programs can just call
// pmu_setup and pmu_control directly (which are defined in user.h and point to usys.S).

// Let's assume for now we don't need extra C wrappers in a separate pmu.c
// The stubs generated by usys.pl and declared in user.h are sufficient.
// If you wanted pmu.c to *define* pmu_setup and pmu_control (e.g. if they were not syscalls),
// then they would be defined here. But since they *are* syscalls, user.h declares them,
// and usys.S provides the implementation.

// If you decide later to have more complex wrapper functions, like:
// int pmu_measure_cycles_and_instructions(unsigned long* cycles, unsigned long* instructions) {
//     // ... logic using pmu_setup and pmu_control ...
//     return 0;
// }
// then pmu.c would be the place for them.


